Application/Models/PhoneBook.cs
using System.ComponentModel.DataAnnotations;
using lang = MultiLanguage.Models.PhoneBook;
namespace Application.Models
{
    public class PhoneBook
    {
        /// <summary>
        /// 姓名
        /// </summary>
        [StringLength(10, ErrorMessageResourceName = "StringMax", ErrorMessageResourceType = typeof(lang))]
        [Display(Name = "姓名", ResourceType = typeof(lang))]
        public string Name { get; set; }

        /// <summary>
        /// 電話
        /// </summary>
        [Display(Name="電話號碼", ResourceType = typeof(lang))]
        public string Numbers { get; set; }
    }
}

Application/Controllers/CultureController.cs
using System.Web;
using System.Web.Mvc;

namespace Application.Controllers
{
    public class CultureController : Controller
    {
        /// <summary>
        /// 切換語系
        /// </summary>
        /// <param name="culture"></param>
        /// <param name="returnUrl"></param>
        /// <returns></returns>
        public ActionResult SetCulture(string culture, string returnUrl)
        {
            Response.Cookies.Add(
                new HttpCookie("_culture")
                {
                    Value = Tools.CultureTool.GetImplementedCulture(culture)
                }
            );
            return Redirect(returnUrl);
        }
    }
}

Application/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Application.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var model = new Models.PhoneBook() { Name = "金貝貝", Numbers = "3345678" };
            return View(model);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Application/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Application/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Application/Views/Home/Index.cshtml
@using lang = MultiLanguage.Views.Home.Index
@model Application.Models.PhoneBook
@{
    ViewBag.Title = "Home Page";
    

}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p> @Html.LabelFor(n => n.Name)  @Html.Encode(Model.Name)  </p>    
    <p> @Html.LabelFor(n => n.Numbers) @Html.Encode(Model.Numbers)</p>    
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
    <p><a href="#" class="btn btn-primary btn-lg">@lang.更多資訊</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Application/Views/Shared/_Layout.cshtml
@using lang = MultiLanguage.AllViews
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li> 
                        <div class="dropdown">
                            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                @lang.目前語言
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                <li>
                                    @Html.ActionLink("正體中文", "SetCulture", "Culture", new { Culture = "zh-TW", returnUrl = this.Request.RawUrl }, null)
                                </li>
                                <li>
                                    @Html.ActionLink("English", "SetCulture", "Culture", new { Culture = "en-US", returnUrl = this.Request.RawUrl }, null)
                                </li>
                            </ul>
                        </div>
                    </li>
                </ul>

            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>